name: Auto Approve README Changes

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    if: github.event.pull_request.user.login != 'github-actions[bot]'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check if only README files changed
      id: check-readme-only
      run: |
        # Get list of changed files
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

        # Check if only README files are changed
        NON_README_FILES=$(echo "$CHANGED_FILES" | grep -v -E '^README\.md$|^readme\.md$|^Readme\.md$|^\.github/.*\.md$' || true)

        if [ -z "$NON_README_FILES" ] && [ -n "$CHANGED_FILES" ]; then
          echo "readme-only=true" >> $GITHUB_OUTPUT
          echo "Only README files changed, will auto-approve"
        else
          echo "readme-only=false" >> $GITHUB_OUTPUT
          echo "Non-README files changed, will not auto-approve"
          echo "Changed files: $CHANGED_FILES"
        fi

    - name: Auto approve PR
      if: steps.check-readme-only.outputs.readme-only == 'true'
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
