name: Auto-approve README-only PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        id: files
        uses: tj-actions/changed-files@v45
        with:
          files: README.md

      - name: Auto approve
        if: steps.files.outputs.only_changed == 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
