name: Release

permissions:
      contents: write
      issues: write
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

    - name: Run tests
      run: ginkgo -v ./main

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v5
      with:
        semantic_version: latest
        extra_plugins: |
          @semantic-release/changelog@6.0.3
          @semantic-release/git@10.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
